const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto'),net=require('node:net');const {spawn}=require('node:child_process');const {Client,Server}=require('ssh2');
const {launchRemoteClaude,remoteBootstrapCommand}=require('../dist-main/claude-remote-launch');const {claudeRemoteBootstrap}=require('../dist-main/claude-remote-bootstrap');const {ClaudeLocalRuntime}=require('../dist-main/claude-local-runtime');const {LocalToolHost}=require('../dist-main/local-tool-host');const {LoopbackForward}=require('../dist-main/loopback-forward');
const waitFor=(events,predicate)=>new Promise((resolve,reject)=>{const stop=Date.now()+10000;function poll(){if(events.some(predicate))return resolve();if(Date.now()>stop)return reject(new Error('remote fixture timeout'));setTimeout(poll,10)}poll();});
test('bootstrap commands carry public code only, and Windows encoded argv preserves Node path literally',()=>{
 const command=remoteBootstrapCommand('windows','C:\\Program Files\\Node\\node.exe');const script=Buffer.from(command.split(' ').at(-1),'base64').toString('utf16le');assert.ok(script.includes("'C:\\Program Files\\Node\\node.exe'"));assert.ok(!script.includes('private-secret'));assert.ok(claudeRemoteBootstrap.includes('agentbridge_ping'));assert.ok(claudeRemoteBootstrap.includes('taskkill.exe'));assert.ok(claudeRemoteBootstrap.includes('disableAllHooks=true'));assert.ok(claudeRemoteBootstrap.includes('--strict-mcp-config'));
});
test('real SSH remote Claude reads friend provider, forwards Mac tools, isolates official mode, and kills remote child on stop', {timeout:30000},async()=>{
 const temp=await fs.mkdtemp(path.join(os.tmpdir(),'ab-claude-ssh-test-')),root=await fs.realpath(temp),friend=path.join(root,'friend'),mac=path.join(root,'mac'),config=path.join(friend,'.claude');await fs.mkdir(config,{recursive:true});await fs.mkdir(mac);const audit=path.join(friend,'audit.json'),marker=path.join(mac,'proof.txt'),fake=path.join(friend,'claude');
 const original=JSON.stringify({env:{ANTHROPIC_AUTH_TOKEN:'friend-fixture-secret',ANTHROPIC_BASE_URL:'https://friend-fixture.invalid',NATIVE_HELPER:'friend-helper'},hooks:{PostToolUse:[]}});await fs.writeFile(path.join(config,'settings.json'),original);await fs.mkdir(path.join(config,'skills','friend-skill'),{recursive:true});await fs.writeFile(path.join(config,'skills','friend-skill','SKILL.md'),'friend native fixture');
 // Current native Claude hides --permission-prompt-tool from --help even though
 // it accepts it. The bridge must reach initialize instead of rejecting help.
 const flags=['--input-format','--output-format','--strict-mcp-config','--tools','--disallowedTools','--setting-sources','--settings','--plugin-dir'];
 await fs.writeFile(fake,`#!${process.execPath}
const fs=require('fs');if(process.argv.includes('--version')){console.log('2.1.170 fixture');process.exit(0)}if(process.argv.includes('--help')){console.log(${JSON.stringify(flags.join(' '))});process.exit(0)}if(process.argv.includes('auth')){console.log(JSON.stringify({loggedIn:true,authMethod:process.env.ANTHROPIC_AUTH_TOKEN?'api_key':'claude.ai',apiProvider:'firstParty'}));process.exit(0)}
const settings=JSON.parse(fs.readFileSync(process.argv[process.argv.indexOf('--settings')+1],'utf8'));fs.writeFileSync(${JSON.stringify(audit)},JSON.stringify({pid:process.pid,mode:!!process.env.ANTHROPIC_AUTH_TOKEN,keyOverride:process.env.ANTHROPIC_API_KEY==='override-fixture-secret',helper:process.env.NATIVE_HELPER,args:process.argv.slice(2),settings}));const mcp=JSON.parse(process.argv[process.argv.indexOf('--mcp-config')+1]).mcpServers.agentbridge_mac;
const out=value=>process.stdout.write(JSON.stringify(value)+'\\n');require('readline').createInterface({input:process.stdin}).on('line',async line=>{const m=JSON.parse(line);if(m.type==='control_request'){out({type:'control_response',response:{subtype:'success',request_id:m.request_id,response:m.request.subtype==='initialize'?{account:{tokenSource:process.env.ANTHROPIC_AUTH_TOKEN?'ANTHROPIC_AUTH_TOKEN':'oauth'},models:[{value:'fixture-model',displayName:'Friend Model'}],commands:[{name:'friend-skill'}]}:{mcpServers:[{name:'agentbridge_mac',status:'connected',tools:[]}]}}});return;}if(m.type==='user'){if(m.message.content[0].text==='wait')return;const response=await fetch(mcp.url,{method:'POST',headers:{Authorization:'Bearer '+process.env.AGENTBRIDGE_MAC_MCP_TOKEN,'Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'mac_shell_execute',arguments:{command:'printf mac-proof > proof.txt'}}})});const result=await response.json();out({type:'assistant',session_id:'11111111-1111-4111-8111-111111111111',message:{id:'main',content:[{type:'text',text:JSON.stringify(result)}]}});out({type:'result',session_id:'11111111-1111-4111-8111-111111111111',usage:{input_tokens:1,cache_read_input_tokens:0,cache_creation_input_tokens:0,output_tokens:2}});}});
`,{mode:0o700});
 const key=crypto.generateKeyPairSync('rsa',{modulusLength:2048,privateKeyEncoding:{format:'pem',type:'pkcs1'},publicKeyEncoding:{format:'pem',type:'spki'}}).privateKey;const server=new Server({hostKeys:[key]}),peers=[],listeners=new Map(),processes=new Set();
 server.on('connection',peer=>{peers.push(peer);peer.on('error',()=>{});peer.on('authentication',ctx=>ctx.method==='password'&&ctx.password==='fixture-password'?ctx.accept():ctx.reject());peer.on('ready',()=>{
 peer.on('session',accept=>{const session=accept();session.on('exec',(accept,reject,info)=>{const stream=accept(),child=spawn('/bin/sh',['-c',info.command],{env:{...process.env,CLAUDE_CONFIG_DIR:config},stdio:'pipe'});processes.add(child);stream.pipe(child.stdin);child.stdout.pipe(stream);child.stderr.pipe(stream.stderr);child.once('close',code=>{processes.delete(child);stream.exit(code||0);stream.end();});stream.on('close',()=>child.stdin.end());stream.on('error',()=>{});child.stdin.on('error',()=>{});});});
 peer.on('request',(accept,reject,name,info)=>{if(name==='tcpip-forward'){let port;const listener=net.createServer(socket=>peer.forwardOut('127.0.0.1',port,'127.0.0.1',socket.remotePort||0,(error,channel)=>{if(error)return socket.destroy();socket.pipe(channel).pipe(socket);channel.on('error',()=>socket.destroy());socket.on('error',()=>channel.destroy());}));listener.listen(info.bindPort,'127.0.0.1',()=>{port=listener.address().port;listeners.set(port,listener);accept(port)});}else if(name==='cancel-tcpip-forward'){listeners.get(info.bindPort)?.close();listeners.delete(info.bindPort);accept();}else reject();});
 });});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const client=new Client();let allowed=false;const host=new LocalToolHost({allowedRoots:[mac],enableShell:true,authorize:()=>allowed});let forward,cli;
 try{await new Promise((resolve,reject)=>{client.once('ready',resolve);client.once('error',reject);client.connect({host:'127.0.0.1',port:server.address().port,username:'fixture',password:'fixture-password',hostVerifier:()=>true});});const endpoint=await host.start();forward=new LoopbackForward(client,endpoint.port);const port=await forward.start();
 const make=(authMode,api)=>{const events=[];const native=new ClaudeLocalRuntime({cwd:mac,authMode,api,permissionMode:'ask',mcp:{url:`http://127.0.0.1:${port}/mcp`,token:endpoint.token},remote:{launch:(args,options)=>launchRemoteClaude(client,{platform:'posix',nodeExecutable:process.execPath,executable:fake,remoteCwd:friend,args,...options})},onEvent:event=>events.push(event)});return{native,events};};
 let instance=make('api');cli=instance.native;let status=await cli.start();assert.equal(status.runtimeLocation,'remote');assert.equal(status.models[0].displayName,'Friend Model');assert.equal(status.commands[0].name,'friend-skill');
 let captured=JSON.parse(await fs.readFile(audit,'utf8'));assert.equal(captured.mode,true);assert.equal(captured.helper,'friend-helper');assert.equal(captured.settings.disableAllHooks,true);assert.ok(!JSON.stringify(captured).includes('friend-fixture-secret'));assert.ok(!JSON.stringify(captured.args).includes(endpoint.token));assert.ok(captured.args.includes('--strict-mcp-config'));assert.ok(captured.args.includes('--disallowedTools'));
 await cli.send({requestId:'denied',prompt:'write'});await waitFor(instance.events,e=>e.type==='done'&&e.requestId==='denied');await assert.rejects(fs.stat(marker),{code:'ENOENT'});allowed=true;await cli.send({requestId:'allowed',prompt:'write',conversationId:'11111111-1111-4111-8111-111111111111'});await waitFor(instance.events,e=>e.type==='done'&&e.requestId==='allowed');assert.equal(await fs.readFile(marker,'utf8'),'mac-proof');await assert.rejects(fs.stat(path.join(friend,'proof.txt')),{code:'ENOENT'});
 await cli.send({requestId:'cancel',prompt:'wait',conversationId:'11111111-1111-4111-8111-111111111111'});captured=JSON.parse(await fs.readFile(audit,'utf8'));await cli.cancel('cancel');assert.throws(()=>process.kill(captured.pid,0),{code:'ESRCH'});await cli.stop();
 instance=make('official');cli=instance.native;await cli.start();captured=JSON.parse(await fs.readFile(audit,'utf8'));assert.equal(captured.mode,false);assert.equal(captured.helper,'friend-helper');assert.ok(captured.args.includes('--plugin-dir'));await cli.stop();
 instance=make('api',{apiKey:'override-fixture-secret',baseUrl:'https://override.invalid'});cli=instance.native;await cli.start();captured=JSON.parse(await fs.readFile(audit,'utf8'));assert.equal(captured.keyOverride,true);assert.equal(captured.mode,false);assert.ok(!JSON.stringify(captured).includes('override-fixture-secret'));await cli.stop();assert.equal(await fs.readFile(path.join(config,'settings.json'),'utf8'),original);
 instance=make('api');cli=instance.native;await cli.start();await cli.send({requestId:'disconnect',prompt:'wait'});captured=JSON.parse(await fs.readFile(audit,'utf8'));client.destroy();await waitFor([captured],()=>{try{process.kill(captured.pid,0);return false;}catch{return true;}});
 }finally{await cli?.stop();forward?.stop();await host.stop();client.end();for(const peer of peers)peer.end();for(const listener of listeners.values())listener.close();for(const child of processes)child.kill('SIGKILL');await new Promise(resolve=>server.close(resolve));await fs.rm(root,{recursive:true,force:true});}
});
