const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const {fixture}=require('./helpers/relay-fixture.cjs'),{ClaudeLocalRuntime}=require('../dist-main/claude-local-runtime'),{launchRemoteClaude}=require('../dist-main/claude-remote-launch'),{claudeSubscriptionSummary}=require('../dist-main/runtime-usage');
test('OAuth percentage is always 0–100 and ISO resets are parsed; unknowns remain unknown',()=>{const q=claudeSubscriptionSummary({windows:{five_hour:{utilization:1,resets_at:'2026-10-08T12:00:00Z'},seven_day:{utilization:0,resets_at:null},seven_day_opus:{utilization:NaN}}});assert.equal(q.windows[0].remainingPercent,99);assert.equal(q.windows[0].resetsAt,Date.parse('2026-10-08T12:00:00Z')/1000);assert.equal(q.windows[1].remainingPercent,100);assert.equal(q.windows[1].resetsAt,null);assert.equal(q.windows.length,2);});
test('remote TLS quota refresh filters secrets, enables native compaction, and next-turn threshold changes reach process',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'agentbridge-usage-test-')),config=path.join(root,'.claude');await fs.mkdir(config);await fs.writeFile(path.join(config,'.credentials.json'),JSON.stringify({claudeAiOauth:{accessToken:'fixture-oauth-never-leaves-runtime',expiresAt:Date.now()+100000}}));await fs.writeFile(path.join(config,'.claude.json'),JSON.stringify({autoCompactEnabled:false,unrelated:'preserved'}));
 const mock=path.join(root,'mock.cjs'),fake=path.join(root,'claude');
 await fs.writeFile(mock,`const {EventEmitter}=require('events');require('https').request=(url,options,callback)=>{if(url!=='https://api.anthropic.com/api/oauth/usage'||options.headers.Authorization!=='Bearer fixture-oauth-never-leaves-runtime')throw Error('wrong usage route');const req=new EventEmitter();req.setTimeout=()=>req;req.end=()=>{const res=new EventEmitter();res.statusCode=200;callback(res);queueMicrotask(()=>{res.emit('data',Buffer.from(JSON.stringify({five_hour:{utilization:1,resets_at:'2026-10-08T12:00:00Z',secret:'must-filter'},seven_day:{utilization:40,resets_at:null},token:'must-filter'})));res.emit('end');});};return req;};`);
 await fs.writeFile(fake,`#!${process.execPath}\nif(process.argv.includes('--version')){console.log('2.1.170 fixture');process.exit(0)}if(process.argv.includes('auth')){if(process.env.CLAUDE_CONFIG_DIR!==${JSON.stringify(config)})process.exit(2);console.log(JSON.stringify({loggedIn:true,authMethod:'claude.ai',apiProvider:'firstParty'}));process.exit(0)}const out=v=>process.stdout.write(JSON.stringify(v)+'\\n');require('readline').createInterface({input:process.stdin}).on('line',line=>{const m=JSON.parse(line);if(m.type==='control_request')out({type:'control_response',response:{subtype:'success',request_id:m.request_id,response:{account:{tokenSource:'oauth'},models:[]}}});if(m.type==='user'){out({type:'system',subtype:'compact_boundary',compact_metadata:{trigger:'auto',pre_tokens:90000}});out({type:'assistant',session_id:'11111111-1111-4111-8111-111111111111',message:{id:'answer',content:[{type:'text',text:process.env.CLAUDE_AUTOCOMPACT_PCT_OVERRIDE}]}});out({type:'result',session_id:'11111111-1111-4111-8111-111111111111',usage:{input_tokens:1,output_tokens:1,cache_read_input_tokens:0,cache_creation_input_tokens:0}});}});`,{mode:0o700});
 const f=await fixture({root,commandEnv:{...process.env,CLAUDE_CONFIG_DIR:path.join(root,'other-profile'),NODE_OPTIONS:'--require '+mock}}),events=[],cli=new ClaudeLocalRuntime({cwd:root,authMode:'official',autoCompactPercent:70,remote:{launch:(args,options)=>launchRemoteClaude(f.conn.asRuntimeClient(),{platform:'posix',nodeExecutable:process.execPath,executable:fake,remoteCwd:root,configDir:config,args,...options})},onEvent:e=>events.push(e)});
 try{await cli.start();assert.equal(cli.status().account.authenticated,true);assert.equal(cli.status().claudeConfigDir,config);const q=await cli.refreshQuota();assert.equal(q.windows[0].remainingPercent,99);assert.equal(q.windows[1].remainingPercent,60);assert.ok(!JSON.stringify(q).includes('must-filter'));assert.ok(!JSON.stringify(events).includes('fixture-oauth'));assert.deepEqual(JSON.parse(await fs.readFile(path.join(config,'.claude.json'),'utf8')),{autoCompactEnabled:true,unrelated:'preserved'});
 const a=await cli.sendAndWait({prompt:'first',autoCompactPercent:70});assert.equal(a.text,'70');const b=await cli.sendAndWait({prompt:'next',conversationId:a.conversationId,autoCompactPercent:60});assert.equal(b.text,'60');assert.equal(events.filter(e=>e.type==='contextCompacted').length,2);assert.equal(events.find(e=>e.type==='contextCompacted').postTokens,null);
 }finally{await cli.stop();await f.close();await fs.rm(root,{recursive:true,force:true});}
});
