import {ConnectionForm} from './LegacyViews';
import {RuntimeStatus,type RuntimeConnection} from './RuntimeControls';
export function ClaudeSettings(p:{mode:'official'|'api';setMode:(value:'official'|'api')=>void;runtime:RuntimeConnection|null;busy:boolean;working:boolean;onDisconnect:()=>void;onRefresh:()=>void;runtimeBusy:boolean;baseUrl:string;setBaseUrl:(value:string)=>void;apiKey:string;setApiKey:(value:string)=>void;model:string;setModel:(value:string)=>void;executable:string;setExecutable:(value:string)=>void;nodeExecutable:string;setNodeExecutable:(value:string)=>void;remoteCwd:string;setRemoteCwd:(value:string)=>void;localCwd:string;setLocalCwd:(value:string)=>void;chooseLocal:()=>void;platform:'auto'|'windows'|'posix';setPlatform:(value:'auto'|'windows'|'posix')=>void;permission:'ask'|'project'|'full';setPermission:(value:'ask'|'project'|'full')=>void;draft:any;setDraft:(value:any)=>void;onSave:()=>void;onConnect:()=>void}){
 const disabled=p.busy||!!p.runtime;
 return <><div className="segmented claude-auth-modes" aria-label="Claude 登入模式">{([['official','朋友的官方帳號'],['api','朋友的 API／供應商']] as const).map(([mode,label])=><button key={mode} disabled={p.working||p.busy} className={p.mode===mode?'active':''} onClick={()=>p.setMode(mode)}>{label}</button>)}</div>
 <p className="settings-intro">Claude Code、帳號與模型連線在朋友的電腦執行；檔案、命令、電腦與瀏覽器操作在這台 Mac。直接在對話框交代工作，不需要指定 MCP 名稱。</p>
 {p.runtime&&<><RuntimeStatus runtime={p.runtime} onRefresh={p.onRefresh} busy={p.runtimeBusy}/><button className="text-button runtime-disconnect" disabled={p.working} onClick={p.onDisconnect}>中斷朋友的 Claude Runtime</button></>}
 <div className="runtime-configuration"><label>朋友主機系統<select aria-label="Claude Runtime 主機系統" value={p.platform} disabled={disabled} onChange={e=>p.setPlatform(e.target.value as 'auto'|'windows'|'posix')}><option value="auto">自動辨識（建議）</option><option value="windows">Windows</option><option value="posix">macOS / Linux / WSL</option></select></label>
 <label>朋友的 Claude Code 執行檔<input aria-label="朋友的 Claude Code 執行檔" value={p.executable} onChange={e=>p.setExecutable(e.target.value)} placeholder={p.platform==='windows'?'自動尋找原生 claude.exe，或填入完整路徑':'claude'} disabled={disabled}/><small>Windows 使用原生 .exe，不使用 .cmd 包装器。</small></label>
 <label>朋友主機 Node.js<input aria-label="Claude Runtime Node.js" value={p.nodeExecutable} onChange={e=>p.setNodeExecutable(e.target.value)} placeholder="node" disabled={disabled}/><small>Node.js 只負責 SSH 通訊橋接，Claude Code 仍用朋友安裝的原生程式。</small></label>
 <label>朋友主機設定資料夾（選填）<input aria-label="Claude Runtime 設定資料夾" value={p.remoteCwd} onChange={e=>p.setRemoteCwd(e.target.value)} placeholder="留白使用朋友的家目錄" disabled={disabled}/><small>載入這個資料夾的 Claude Skills／設定；你的工作檔案仍在 Mac。</small></label>
 {p.mode==='api'&&<><label>API 端點（選填）<input aria-label="Claude API 端點" value={p.baseUrl} onChange={e=>p.setBaseUrl(e.target.value)} placeholder="留白沿用朋友主機的供應商" disabled={disabled}/></label><label>API Key（選填）<input aria-label="Claude API Key" type="password" autoComplete="off" value={p.apiKey} onChange={e=>p.setApiKey(e.target.value)} placeholder="留白沿用朋友既有設定，不儲存本次金鑰" disabled={disabled}/></label><label>起始模型 ID（選填）<input aria-label="Claude API 起始模型" value={p.model} onChange={e=>p.setModel(e.target.value)} placeholder="連線後可切換模型" disabled={disabled}/></label></>}
 <label>這台 Mac 的工作資料夾<div className="inline-field"><input aria-label="Claude Code 工作資料夾" value={p.localCwd} onChange={e=>p.setLocalCwd(e.target.value)} disabled={disabled}/><button className="secondary compact" disabled={disabled} onClick={p.chooseLocal}>選擇</button></div></label>
 <label>Mac 操作權限<select aria-label="Claude Code 操作權限" value={p.permission} disabled={p.busy} onChange={e=>p.setPermission(e.target.value as 'ask'|'project'|'full')}><option value="project">讀取工作檔案自動允許，其餘操作先詢問</option><option value="ask">工具操作先詢問</option><option value="full">最高權限：所有操作不逐次詢問</option></select><small>設定會保留並從新工作套用；macOS 系統權限仍須開啟。</small></label></div>
 <ConnectionForm draft={p.draft} setDraft={p.setDraft} onSave={p.onSave} onConnect={p.onConnect} busy={p.busy||p.working} connectLabel="連接朋友的 Claude Runtime"/>
 <p className="settings-tip">{p.mode==='official'?'官方模式隔離朋友的自訂 API 設定；請朋友在他的電腦完成 claude auth login --claudeai 後連線。':'API 模式讀取朋友的供應商設定；本次輸入透過 SSH 傳給朋友的程序，不寫入設定檔。'}模型選項由朋友的 CLI 回報，連通性以實際回覆確認。</p>
 <p className="settings-tip">分離執行時，朋友主機的 hooks 與原有 MCP 暫不執行，以免工作落在他的電腦；Skills／指令仍由原生 CLI 載入，工作工具由 Mac 通道提供。</p></>;
}
