import type { DoctorReport } from './global';
import type { RuntimeConnection } from './RuntimeControls';
import { Glyph } from './StudioUI';

export function MacToolsPanel({computerProvider,onProvider,services,exposure,httpHealth,onHttp,runtime,doctor,permissionDiagnostics,onDiagnostics,localTools,toolHealth,busy,onHealth,onRecover,onPermissions,onConnect,onRefresh,onPrompt}:{computerProvider:any;onProvider:(provider:"bundled"|"open-computer-use")=>void;services:any[];exposure:any;httpHealth:string|null;onHttp:(name:"computer"|"browser",action:"start"|"stop"|"health")=>void;runtime:RuntimeConnection|null;doctor:DoctorReport|null;permissionDiagnostics:string|null;onDiagnostics:()=>void;localTools:RuntimeConnection['macTools']|null;toolHealth:string|null;busy:boolean;onHealth:()=>void;onRecover:()=>void;onPermissions:()=>void;onConnect:()=>void;onRefresh:()=>void;onPrompt:(prompt:string)=>void}) {
  const macTools=runtime?.macTools||localTools;
  const capabilities = [
    { name:'專案檔案', icon:'folder', ready:runtime?.capabilities.fileShell, detail:runtime?.executorEnvironment?.cwd||'選擇這台 Mac 的工作資料夾' },
    { name:'終端機與命令', icon:'terminal', ready:runtime?.executorConnected, detail:'在 Mac 執行測試、建置與命令' },
    { name:'電腦與應用程式', icon:'computer', ready:macTools?.computer.startsWith('connected'), detail:'查看畫面、點擊、輸入與切換應用程式' },
    { name:'瀏覽器', icon:'search', ready:macTools?.browser.startsWith('connected'), detail:'在 Mac 上開啟瀏覽器、閱讀與操作網頁' },
  ];
  return <section className="page-shell mac-tools-page">
    <div className="page-heading"><div><span className="page-eyebrow">這台 Mac</span><h1>電腦與工具</h1><p>在對話中交代工作，Agent 會使用你允許的本機工具。</p></div><button className="secondary" onClick={onRefresh}><Glyph name="refresh" size={17}/>更新狀態</button></div>
    <div className="mac-tools-device"><Glyph name="link" size={20}/><div><b>{runtime?'Runtime 已連線':localTools?.ok?'Mac 工具已接通 · 尚未連接模型':'尚未連接模型 Runtime'}</b><p>{runtime?`${runtime.hostName||'遠端 Runtime'} · 工具執行位置：這台 Mac`:'朋友的 Windows 保留登入與模型連線；這台 Mac 提供工具。'}</p></div><button className="secondary compact" onClick={onConnect}>連線設定</button></div>
    <div className="mac-tools-permissions"><h3>電腦工具來源</h3><label>電腦操作使用 <select aria-label="電腦工具來源" value={computerProvider?.provider||'bundled'} disabled={busy||!!runtime||services.some(s=>['running','starting'].includes(s.status))} onChange={event=>onProvider(event.target.value as 'bundled'|'open-computer-use')}><option value="bundled">內建 Computer Use</option><option value="open-computer-use" disabled={!computerProvider?.externalAvailable}>Open Computer Use（既有安裝）</option></select></label><p>模型工具與電腦 HTTP 共用這個來源。切換前請中斷模型並停止 HTTP；若所選來源失敗，請明確改選另一個來源。</p>{computerProvider&&<p>{computerProvider.label}</p>}</div>
    <div className="mac-tools-grid">{capabilities.map(capability=><div className="mac-tools-capability" key={capability.name}><Glyph name={capability.icon} size={24}/><div><h3>{capability.name}</h3><p>{capability.detail}</p></div><span className={capability.ready?'connected':''}>{capability.ready?'已接通':'未接通'}</span></div>)}</div>
    <div className="mac-tools-permissions"><h3>工具通道檢查</h3><p>Runtime 透過獨立工具通道連接這台 Mac，不需要開啟選用的 HTTP 端點。檢查會呼叫所選電腦工具的唯讀功能，並讀取瀏覽器分頁。</p><button className="secondary compact" disabled={busy} onClick={onHealth}>檢查工具是否可用</button> <button className="secondary compact" disabled={busy} onClick={onRecover}>重新連接工具</button>{toolHealth&&<p role="status">{toolHealth}</p>}</div>
    <div className="mac-tools-permissions"><h3>HTTP 工具連線</h3><p>供其他 MCP 用戶端使用，與模型的獨立工具通道分開啟停。預設僅限本機；遠端曝光只允許 Tailscale。這些端點不提供專案檔案或命令工具。</p><p>目前模式：{exposure?.mode||'讀取中'} · 位址 {exposure?.bindHost||'待確認'}</p>{(['computer','browser'] as const).map(name=>{const service=services.find(s=>s.name===name);const running=['running','starting'].includes(service?.status);const healthy=service?.health?.ok&&running;return <div key={name}><span>{name==='computer'?'電腦 HTTP':'瀏覽器 HTTP'} · {healthy?'已接通':running?'已啟動，待檢查':'未啟動'}</span><button className="secondary compact" disabled={busy||running||!['tailscale','localhost'].includes(exposure?.mode)} onClick={()=>onHttp(name,'start')}>啟動</button><button className="secondary compact" disabled={busy||!running} onClick={()=>onHttp(name,'health')}>檢查連線</button><button className="secondary compact" disabled={busy||!running} onClick={()=>onHttp(name,'stop')}>停止</button>{service?.url&&<p>{service.url}{healthy&&` · ${service.health.source} · ${service.health.toolCount} 個工具 · ${new Date(service.health.checkedAt).toLocaleTimeString()} 檢查成功`}</p>}</div>;})}{httpHealth&&<p role="status">{httpHealth}</p>}</div>
    <div className="mac-tools-examples"><h3>從對話開始</h3>{[['查看畫面','查看我 Mac 現在的畫面，告訴我開啟了哪些應用程式。'],['分析專案','讀取這台 Mac 工作資料夾的 README，分析專案並列出下一步。'],['執行測試','在這台 Mac 的工作資料夾執行測試，分析失敗原因。'],['使用瀏覽器','在這台 Mac 的瀏覽器開啟網頁，先詢問我要處理哪個網站。']].map(([label,prompt])=><button key={label} onClick={()=>onPrompt(prompt)}><span>{label}</span><Glyph name="arrow" size={16}/></button>)}</div>
    <div className="mac-tools-permissions"><h3>macOS 系統權限</h3><button className="secondary compact" disabled={busy||computerProvider?.provider==='open-computer-use'} onClick={onPermissions}>請求 macOS 授權</button> <button className="secondary compact" onClick={onDiagnostics}>檢查權限來源</button>{permissionDiagnostics&&<p role="status">{permissionDiagnostics}</p>}{doctor?.checks.filter(check=>['accessibility','screen_recording'].includes(check.id)).map(check=><div key={check.id}><span>{check.label}</span><b>{check.state==='ok'?'已授權':check.state==='fail'?'需要授權':'未回報'}</b>{check.state!=='ok'&&<button className="text-button" onClick={()=>void window.agentBridge.system.openExternal(check.id==='accessibility'?'x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility':'x-apple.systempreferences:com.apple.preference.security?Privacy_ScreenCapture')}>開啟系統設定</button>}</div>)}<p>{computerProvider?.provider==='open-computer-use'?'Open Computer Use 不回報權限旗標；未回報不代表未授權。請以查看畫面與應用程式的實際結果確認。 ':''}工具已接通表示服務可呼叫。螢幕、點擊與輸入會在使用時檢查系統權限；最高權限模式不逐次詢問操作，macOS 系統授權仍由系統管理。</p></div>
  </section>;
}
