import {useEffect,useRef,useState} from 'react';
export function RelayFiles({profile}:{profile:any}){
 const [folder,setFolder]=useState(''),[items,setItems]=useState<any[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[transfer,setTransfer]=useState<string|null>(null);
 const refresh=async(target=folder)=>{setBusy(true);try{const result=await window.agentBridge.network.files({profileId:profile.id,url:profile.relayUrl,path:target});setFolder(result.path);setItems(result.items);setMessage('');}catch(e){setMessage(String(e));}finally{setBusy(false);}};
 useEffect(()=>{void refresh('');},[profile.id,profile.relayUrl]);
 useEffect(()=>window.agentBridge.network.onEvent(e=>{if(e.type==='transfer'&&e.id===transfer)setMessage(`已傳輸 ${(e.bytes/1024).toFixed(1)} KiB`);}),[transfer]);
 const move=async(direction:string,target:string)=>{const id=crypto.randomUUID();setTransfer(id);try{const result=await window.agentBridge.network.transfer({id,profileId:profile.id,url:profile.relayUrl,direction,path:target});setMessage(result.cancelled?'已取消':`完成 · ${result.bytes} bytes`);await refresh();}catch(e){setMessage(String(e));}finally{setTransfer(null);}};
 return <section className="page-shell"><h1>遠端檔案</h1><p>HTTPS 傳輸 · 單檔上限 64 MiB · 上傳保留同名既有檔案</p><div className="form-actions"><button className="secondary" disabled={busy||!!transfer} onClick={()=>void refresh(folder.split('/').slice(0,-1).join('/'))}>上一層</button><button className="secondary" disabled={busy||!!transfer} onClick={()=>void refresh()}>更新</button><button className="secondary" disabled={busy||!!transfer} onClick={()=>void move('upload',folder)}>上傳檔案</button>{transfer&&<button className="secondary" onClick={()=>void window.agentBridge.network.cancelTransfer(transfer)}>取消傳輸</button>}</div><p>{folder||'Gateway 工作資料夾'} · {message}</p><ul className="relay-file-list">{items.map(item=><li key={item.path}><button disabled={busy||!!transfer} onClick={()=>item.isDirectory?void refresh(item.path):void move('download',item.path)}>{item.isDirectory?'📁':'↓'} {item.name}</button><small>{item.isDirectory?'資料夾':`${item.size} bytes`}</small></li>)}</ul></section>;
}
export function RelayTerminal({profile}:{profile:any}){
 const [output,setOutput]=useState(''),[input,setInput]=useState(''),[status,setStatus]=useState('連線中…'),id=useRef<string|null>(null);
 useEffect(()=>{let disposed=false;const off=window.agentBridge.network.onEvent(e=>{if(e.id!==id.current)return;if(e.type==='terminal')setOutput(old=>(old+e.text).slice(-1000000));if(e.type==='terminalClosed')setStatus('命令通道已中斷，請重新開啟。');});window.agentBridge.network.terminal({profileId:profile.id,url:profile.relayUrl}).then(value=>{if(disposed)void window.agentBridge.network.terminalClose(value.id);else{id.current=value.id;setStatus('已連線');}}).catch(e=>setStatus(String(e)));return()=>{disposed=true;off();if(id.current)void window.agentBridge.network.terminalClose(id.current);};},[profile.id,profile.relayUrl]);
 return <section className="page-shell"><h1>遠端命令通道</h1><p>{status} · 支援指令與輸出串流；此通道沒有虛擬終端機，完整互動式 TUI 請用 SSH。</p><pre className="relay-terminal-output">{output}</pre><form onSubmit={e=>{e.preventDefault();if(id.current)void window.agentBridge.network.terminalWrite(id.current,input+'\n');setInput('');}}><input aria-label="遠端指令" value={input} onChange={e=>setInput(e.target.value)}/><button className="secondary" disabled={!id.current}>執行</button></form></section>;
}
